### ISSUE TITLE
无法爬取window.open的url

### ISSUE THREAD

**Issue by EvilHat-K** [chaitin/rad#12]
使用默认的参数运行 ./rad_linux_amd64 -t http://testphp.vulnweb.com/ --text-output testphp.vulnweb.com.txt
发现如http://testphp.vulnweb.com/artists.php 这个页面中的 http://testphp.vulnweb.com/comment.php?aid=1 无法抓取到. 不知道是程序的抓取方法没匹配到还是说要设置什么参数

**Comment by chinaykc** [comment]
已经确认问题，会在下个版本修复，感谢。

**Comment by chinaykc** [comment]
已经于0.2版本修复
