### ISSUE TITLE
新弹出的浏览器窗口里的内容和流量无法抓包

### ISSUE THREAD

**Issue by hilson946** [chaitin/rad#15]
新弹出的浏览器窗口里的内容和流量无法抓包，如下图情况
![image](https://user-images.githubusercontent.com/61529453/90466325-17b53a00-e144-11ea-9e9b-8785ba8444ff.png)

**Comment by chinaykc** [comment]
问题同[https://github.com/chaitin/rad/issues/12](https://github.com/chaitin/rad/issues/12)

已经确认问题，会在下个版本修复，感谢。
