### ISSUE TITLE
加上捕获ctrl+c比较方便中止

### ISSUE THREAD

**Issue by Martin2877** [chaitin/rad#22]
![image](https://user-images.githubusercontent.com/26109420/95813750-2dfa0380-0d4b-11eb-8ad0-641a65068cc8.png)

不然停不下来

**Comment by chinaykc** [comment]
1. 有捕获。
2. 在做一些清理工作。
3. 会进一步优化退出的速度。

感谢反馈

**Comment by chinaykc** [comment]
0.3版本优化了退出逻辑，会在ctrl + c 两秒内退出。
