### ISSUE TITLE
--wait-login与-http-proxy联合使用问题

### ISSUE THREAD

**Issue by Liu296324429** [chaitin/rad#4]
命令：./rad_darwin_amd64 -t https://xxx.com/login --wait-login -http-proxy 127.0.0.1:7777
--wait-login命令如何与-http-proxy一起使用？谢谢。
--wait-login打开一个新的chrome,终端监听了地址端口，新的chrome装不了插件。

**Comment by savior325** [comment]
+1很多验证码登录的场景，同时想和xary联动

**Comment by chinaykc** [comment]
装不了插件是预期行为，暂无法支持。-wait-login -http-proxy一起使用经过验证不存在问题，确实使用了代理。
