### ISSUE TITLE
能否加一个批量的功能，只能扫描一个url，感觉有些鸡肋

### ISSUE THREAD

**Issue by F1xing** [chaitin/rad#46]

**Comment by 0lh** [comment]
https://github.com/timwhitez/rad-xray

**Comment by ox01024** [comment]
自己封装 剑已经给你了 至于你是御剑飞行 还是一剑破山河 都看自己了

**Comment by F1xing** [comment]
我也想自己封装，请问源码在哪里呢？

**Comment by ox01024** [comment]
你就当个二进制可执行程序调用就行

**Comment by F1xing** [comment]
我要会那个，我自己开发一个不好吗？

**Comment by ox01024** [comment]
改行吧

**Comment by hkxueqi** [comment]
自己python写一个，循环函数，不会写看编程手册wiki，再不会github有那么多批量脚本的实现；如xray批量脚本“pppxray”，去改cmd命令总会吧。
