### ISSUE TITLE
Backdoor!

### ISSUE THREAD

**Issue by byposeidon** [chaitin/rad#67]
Why did you embed a backdoor in the application?

- Don't use this non-open source app while CrawlerGo is available.

**Comment by 4ra1n** [comment]
Please give a more detailed description of how to prove the existence of the backdoor?

**Comment by Jarcis-cy** [comment]
Are you talking about leakless?
Leakless is a component within the rod framework. To ensure that all processes (including related browser processes) started by rad can be killed when it exits

**Comment by Jarcis-cy** [comment]
Are you talking about leakless?
Leakless is a component within the rod framework. To ensure that all processes (including related browser processes) started by rad can be killed when it exits
