### ISSUE TITLE
报错提示:panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by shadow1ng** [chaitin/rad#7]
.\rad_windows_amd64.exe --http-proxy 127.0.0.1:8080 -t https://xxxx/ -text-output result.txt
![image](https://user-images.githubusercontent.com/39651966/90097112-c5e96a00-dd67-11ea-8b6c-a3d68afb1ca2.png)

**Comment by chinaykc** [comment]
已经修复panic的问题。 关于chrome配置问题可参考： #23 中网友的回复。
