### ISSUE TITLE
设置不允许url关键字不起作用

### ISSUE THREAD

**Issue by g3tSh311** [chaitin/rad#8]
设置如图，

设置register，forum，search为不爬取的关键字，但是rad还是爬取了包含这几个关键字的url,请问是我yaml语法错误吗？
![dSPigU.png](https://s1.ax1x.com/2020/08/13/dSPigU.png)

**Comment by fumengze** [comment]
同求，最好写个样例，方便编写。

**Comment by chinaykc** [comment]
关键字不支持正则。可以考虑直接写URL过滤正则。
